### ISSUE TITLE
Unable to download Bombcast

### ISSUE THREAD

**Issue by JOLLY6R33NGIANT** [lightpohl/gb-dl#11]
When attempting to download the video feed of the Bombcast getting a ERR_NON_2XX_3XX_RESPONSE error.

**Comment by lightpohl** [comment]
Hey @JOLLY6R33NGIANT,

I'm not seeing the error with the command below. My guess is the API was having some issues for a bit and fixed itself.

`npx gb-dl --api-key REDACTED --show-name "Giant Bombcast" --video-number 0`

Definite re-open if it persists and provide the command and full error output if you can!

**Comment by JOLLY6R33NGIANT** [comment]
When I use the script for shows it seems to be working so that's fine. But when I try and individual command it errors out like posted. 
Command used : `npx gb-dl --api-key "APIKEY" --video-guid "https://www.giantbomb.com/shows/giant-bombcast-440-the-live-one-premium/2970-12499/premium-video" --add-guid-prefix --archive`

Error message: `node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (C:\Users\Kyle\AppData\Roaming\npm\node_modules\gb-dl\node_modules\got\dist\source\as-promise\index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1661707991605,
    socket: 1661707991605,
    lookup: 1661707991605,
    connect: 1661707991635,
    secureConnect: 1661707991671,
    upload: 1661707991671,
    response: 1661707991841,
    end: 1661707991852,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 0,
      tcp: 30,
      tls: 36,
      request: 0,
      firstByte: 170,
      download: 11,
      total: 247
    }
  }
}`

**Comment by lightpohl** [comment]
Thank you!

It looks like the entire API is down for video info. You can see the error directly by visiting this URL: `https://www.giantbomb.com/api/video/2970-21598/?api_key=KEY_HERE`

I'll see if it resolves itself later today and report it in the forums if it doesn't. 👍

**Comment by JOLLY6R33NGIANT** [comment]
Thanks I appreciate it. Only noticed because the first 20 shows under the Bombcast are Alt+F1 videos so I thought something was wrong and would have to do it individually.

**Comment by lightpohl** [comment]
Yeah, really not sure what is going on there! Imagine it has something to do with the video migrations since the relaunch.

I pushed up a version with `--health-check` option to hopefully make this easier to debug next time. Crossing my fingers it's an easy fix for them. 🤞

**Comment by lightpohl** [comment]
Opened a thread over on the Giant Bomb forums: https://www.giantbomb.com/forums/api-developers-3017/videoguid-endpoint-is-throwing-an-error-1905870/

**Comment by lightpohl** [comment]
This has been resolved! Thanks again for the report. 🚀
