### ISSUE TITLE
Unable to find recently created shows

### ISSUE THREAD

**Issue by lrkissling** [lightpohl/gb-dl#12]
I tried to use gb-dl to get info for an episode from Blight Club: `npx gb-dl --api-key <KEY> --show-name "Blight Club" --video-number 0 --info`

I receive the following error: `no show found for Blight Club`

The GB API does have a show object for Blight Club, however it can only be found by offsetting the video_shows API request:

https://www.giantbomb.com/api/video_shows/?api_key=KEY&format=json&offset=100

(It's not clear there are >100 shows due to the API erroneously having `number_of_total_results` set to the same thing as `number_of_page_results`)

**Comment by lightpohl** [comment]
Hey! Thanks for the report — I have a hacky workaround that will work for now (will work until Giant Bomb >200 shows). I'll get the fix pushed up here momentarily and open a bug thread over on Giant Bomb.

**Comment by lightpohl** [comment]
Alrighty! Fix is in and available in v3.1.2.

 @lrkissling: Running your command with `npx gb-dl@latest` should get you the latest version next time you use it. 💪

**Comment by lrkissling** [comment]
Wow, you're fast! Thanks!
