### ISSUE TITLE
[Bug] Inaccurate maximum bitrate URL

### ISSUE THREAD

**Issue by TheIllusiveC4** [lightpohl/gb-dl#13]
Version: 3.1.2

This is related to the previous issue: https://github.com/lightpohl/gb-dl/issues/4

Although the current workaround worked at the time, there have been two changes since then.

Firstly, the videos on 2021-06-30 and afterwards began encoding to 5000 kbps instead of 4000. You can see this in the "Quick Look: Twelve Minutes" video with GUID 2300-17151.

Secondly, the videos on 2022-03-16 and afterwards use a different template entirely (i.e. "vf_ql_tunic_031622_027_1_1080h5000k.mp4" from "Quick Look: Tunic" with GUID 2300-17633).

To accurately grab the maximum bitrate 8000 kbps URLs for these videos, updates would need to be made to the code to include both of the above situations.

**Comment by lightpohl** [comment]
Thank you the detailed report! I'll get an update out here shortly that should remedy the mentioned issues. 👍

**Comment by lightpohl** [comment]
Thanks again! This should be resolved in v3.1.3. Running the command with `npx gb-dl@latest` should pull the version with the fix.
