### ISSUE TITLE
confusion on how to use the date parameters

### ISSUE THREAD

**Issue by stuffinator** [lightpohl/gb-dl#15]
Hey there, first of all thanks for developing this nice little cli tool. It really saves a lot of time.

I want to download all unprofessional fridays from 2014 and I'm using the following command for testing purpose, before I write a script around it.

`npx gb-dl --api-key <super_secret_api_key> --video-name "unprofessional fridays" --date-after "03/07/2014" --date-before "12/31/2014" --video-number 0 --video-number-reverse --info`

But according to the info output the video the tool finds is 

```js
{
  api_detail_url: 'https://www.giantbomb.com/api/video/2300-18591/',
  deck: "There's cubes and dinosaurs EVERYWHERE.",
  guid: '2300-18591',
  id: 18591,
  name: 'Unprofessional Fridays: Unprofessional Fridinosaursday',
  premium: false,
  publish_date: '2023-07-15 10:44:00',
  ...
}
```

Which would be the most recent video. What am I doing wrong?

**Comment by stuffinator** [comment]
Ah ok I got it. I had to add the `--clean` parameter, cause it was constantly using the information from the cache, even though it didn't match the filter.

**Comment by stuffinator** [comment]
Ok found it, the date parmeters don't work with `--video-guid` and `--video-name`.

**Comment by lightpohl** [comment]
Hey! Sorry for the confusion. The GUID and name params use the search API under the hood — there's a chance I missed hooking something up for those params.

I'll investigate later today! 💪

**Comment by lightpohl** [comment]
Oh! Okay! I remember a bit more now! The Giant Bomb API doesn't allow us to specify a date range for returned videos, so the `--date-after` and `--date-before` are simple checks at the end of script to not download videos that fall out of the range. They're not super useful unless you've wrapped `gb-dl` with another script and are [iterating through a show](https://github.com/lightpohl/gb-dl/blob/main/examples/mass-alex.js).

I think you want to combine `--show-name` with `--video-number` for your use case. Something like below after you've found the right number to start with:

```
npx gb-dl --api-key <super_secret_api_key> --show-name "unprofessional fridays" --video-number 0 --video-number-reverse --info
```

**Comment by stuffinator** [comment]
Thanks for clarifying. It works now with your suggestion. I copied the script you have as an example for the mass alex series and changed it to my needs. And that does the trick, thanks mate :)
