### ISSUE TITLE
Append Video ID When Downloading

### ISSUE THREAD

**Issue by Iyagovos** [lightpohl/gb-dl#3]
Hello!

Apologies for this, I'm not certain about the etiquette of commenting on issues on GitHub - using the tool to download Mass Alex today, after yesterday's news, and I was wondering if there's a way to get the tool to add the video ids while downloading. I ask because there's a Plex agent that matches with GB, but it uses the video ids to do so. 

https://github.com/rspeicher/GiantBomb.bundle is the Plex Agent in question.

**Comment by lightpohl** [comment]
@Iyagovos - No apologies necessary! Thanks for the feature request. 😃

TIL about custom Plex media server agent. And this is a really easy addition — I'll add a `--add-guid-prefix` flag this evening that will do just that.

**Comment by Iyagovos** [comment]
Oh wow, amazing! Thank you so much!

**Comment by lightpohl** [comment]
No problem! This is now available in [v2.7.0](https://github.com/lightpohl/gb-dl/releases/tag/v2.7.0).
