### ISSUE TITLE
Download Highest Bitrate Possible

### ISSUE THREAD

**Issue by JOLLY6R33NGIANT** [lightpohl/gb-dl#4]
Apologies for this, I'm new commenting on issues on GitHub. Was using tool to download various series on the site and noticed it only downloads the 4000 bitrate not the 8000. Not a huge deal but I was just curious if it was possible to do so or an API issue. Thanks.

**Comment by lightpohl** [comment]
@JOLLY6R33NGIANT - Hey! It's a good question.

Bad news: The Giant Bomb API isn't returning a download URL with the highest bitrate (8000). I don't think the API has been updated in some time, which would explain its absence.

Good news: I have a potential workaround in mind, which I should have some time later in the week to try out. Basically, just manually checking to see if a video exists at the expected 8000 bitrate URL, and using it if found.

**Comment by lightpohl** [comment]
@JOLLY6R33NGIANT - Workaround was surprisingly easy. Should see those 8k bitrate videos downloaded when available in [v2.7.0](https://github.com/lightpohl/gb-dl/releases/tag/v2.7.0).
