### ISSUE TITLE
New maxBitrate logic doesn't respect archive

### ISSUE THREAD

**Issue by GoldbergAF** [lightpohl/gb-dl#5]
The conversion from 4000->8000 happens after the archive check but before the archive writing. This results in 8000 bitrate files always being redownloaded, since the archive will be checked for the 4000 bitrate file but will have the 8000 bitrate file recorded.

Thanks!

**Comment by lightpohl** [comment]
Whoops! Sorry about that. Will release a patch in just a moment.

**Comment by lightpohl** [comment]
@GoldbergAF - Fixed in [v2.7.1](https://github.com/lightpohl/gb-dl/releases/tag/v2.7.1)!
