### ISSUE TITLE
Allow adding publish_date to filename

### ISSUE THREAD

**Issue by koenvanzuijlen** [lightpohl/gb-dl#6]
First of all thanks a lot for this script. I have been using it happily.

A thing that would make my life easier would be being able to add the publish_date to the filename: https://www.giantbomb.com/api/documentation/#toc-0-47 

Or maybe even making it possible to set a custom filename format based on field available in the API. But I understand that would be a lot more work.

**Comment by lightpohl** [comment]
Thanks a bunch! This is a good ask.

> Or maybe even making it possible to set a custom filename format based on field available in the API. But I understand that would be a lot more work.

I would love to eventually support name templating like I added to [podcast-dl](https://github.com/lightpohl/podcast-dl#templating), but that would take some time and need to be a major version bump.

@koenvanzuijlen - For now, would a simple `--add-date-prefix` in the format `YYYYMMDD` (e.g. "20210507 - Some Title.mp4") be sufficient for your needs?

**Comment by koenvanzuijlen** [comment]
My preferred format is YYYY-MM-DD but if you prefer the other one that is fine too :) 

Thanks!

**Comment by lightpohl** [comment]
Added in [v2.8.0](https://github.com/lightpohl/gb-dl/releases/tag/v2.8.0)! 🚀
